# -*- coding: utf-8 -*-
"""Zahid-DAA-Pertemuan1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGfUUqTM3-ZgpSB9RACwASxJWxT7ijlE

# **Cari nilai KPK dari 3 dan 4**
"""

def fpb(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def kpk(a, b):
    return (a * b) // fpb(a, b)

# Main Program
a = 3
b = 4
result = kpk(a, b)
print(f"KPK dari {a} dan {b} adalah {result}")

"""# **Fungsi untuk menukar posisi dua variabel x dan y, dengan kasus:**
Ada 2 buah: manggis dan pisang. Manggis di piring 1, Pisang di piring 2. Piring 3 kosong.

"""

# Fungsi untuk menukar posisi variabel
def tukar_posisi(x, y):
    temp = x  # Pindahkan manggis dari piring 1 ke piring 3
    x = y     # Pindahkan pisang dari piring 2 ke piring 1
    y = temp  # Pindahkan manggis dari piring 3 ke piring 2
    return x, y

# Main Program
x = "Manggis"
y = "Pisang"
print(f"Sebelum penukaran: Piring 1: {x}, Piring 2: {y}")
x, y = tukar_posisi(x, y)
print(f"Setelah penukaran: Piring 1: {x}, Piring 2: {y}")

"""# **Diketahui sebuah segitiga memiliki ukuran sebagai berikut:**
Alas 25 dan Tinggi 30.
Hitung luas dari segitiga tersebut.
"""

# Fungsi untuk menghitung luas segitiga
def hitung_luas_segitiga(alas, tinggi):
    luas = 0.5 * alas * tinggi
    return luas

# Main Program
alas = 25
tinggi = 30
luas = hitung_luas_segitiga(alas, tinggi)
print(f"Luas segitiga dengan alas {alas} dan tinggi {tinggi} adalah {luas}")

"""# **Luas Jajar Genjang**"""

# Fungsi untuk menghitung luas jajar genjang
def hitung_luas_jajar_genjang(panjang, tinggi):
    luas = panjang * tinggi
    return luas

# Main Program
panjang = 5
tinggi = 3
luas = hitung_luas_jajar_genjang(panjang, tinggi)
print(f"Luas jajar genjang dengan panjang {panjang} dan tinggi {tinggi} adalah {luas}")

"""# **Volume Tabung**"""

# Fungsi untuk menghitung volume tabung
def hitung_volume_tabung(jari_jari, tinggi):
    pi = 3.1416
    volume = pi * (jari_jari ** 2) * tinggi
    return volume

# Main Program
jari_jari = 3
tinggi = 5
volume = hitung_volume_tabung(jari_jari, tinggi)
print(f"Volume tabung dengan jari-jari {jari_jari} dan tinggi {tinggi} adalah {volume}")

"""# **Volume Kerucut**"""

# Fungsi untuk menghitung volume kerucut
def hitung_volume_kerucut(diameter, tinggi):
    pi = 3.1416
    jari_jari = diameter / 2
    volume = (1/3) * pi * (jari_jari ** 2) * tinggi
    return volume

# Main Program
diameter = 5
tinggi = 4
volume = hitung_volume_kerucut(diameter, tinggi)
print(f"Volume kerucut dengan diameter {diameter} dan tinggi {tinggi} adalah {volume}")